In [36]:
import pandas as pd
import numpy as np

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole

from mordred import descriptors,Calculator

In [37]:
def canonical_smiles(smiles):
    mols = [Chem.MolFromSmiles(smi) for smi in smiles]
    smiles = [Chem.MolToSmiles(mol) for mol in mols]
    return smiles

url = 'https://raw.githubusercontent.com/gashawmg/molecular-descriptors/main/Orbital_Energies_input_data.csv'
dataset = pd.read_csv(url)
dataset.shape

(2904, 2)

In [38]:
Canon_SMILES = canonical_smiles(dataset.SMILES)
len(Canon_SMILES)

2904

In [39]:
dataset.head()

                                         SMILES   Energygap
0                           Cc1ccc(cc1)C(F)(F)F  197.749421
1                                   OC(=O)CCCCl  247.493942
2  CC(C)(Oc1ccc(CCNC(=O)c2ccc(Cl)cc2)cc1)C(=O)O  164.712327
3                             Nc1ccc(Cl)c(Cl)c1  169.027707
4                         C[C@@H](CCO)CCC=C(C)C  209.569808

In [40]:
dataset['SMILES'] = Canon_SMILES
dataset

                                            SMILES   Energygap
0                              Cc1ccc(C(F)(F)F)cc1  197.749421
1                                      O=C(O)CCCCl  247.493942
2     CC(C)(Oc1ccc(CCNC(=O)c2ccc(Cl)cc2)cc1)C(=O)O  164.712327
3                                Nc1ccc(Cl)c(Cl)c1  169.027707
4                            CC(C)=CCC[C@@H](C)CCO  209.569808
...                                            ...         ...
2899    c1ccc(P(CCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1  168.649319
2900                               Brc1cccc2sccc12  162.928319
2901               CCOC(=O)N1c2ccccc2C=C[C@@H]1OCC  165.098245
2902                                 c1ccc2sccc2c1  167.958431
2903                                 Cc1cccc(C)c1O  188.369417

[2904 rows x 2 columns]

In [41]:
duplicates_smiles = dataset[dataset['SMILES'].duplicated()]['SMILES'].values
len(duplicates_smiles)

31

In [42]:
dataset[dataset['SMILES'].isin(duplicates_smiles)].sort_values(by=['SMILES'])

                                          SMILES   Energygap
218                                  C1=CCCCCCC1  214.097913
2125                                 C1=CCCCCCC1  214.097913
1901                     C1CC[C@H]2CCCC[C@@H]2C1  251.144790
552                      C1CC[C@H]2CCCC[C@@H]2C1  251.144790
554                                 C=CN1CCCC1=O  190.834900
1808                                C=CN1CCCC1=O  190.835527
2203                                 C=Cc1ccccc1  168.467969
1354                                 C=Cc1ccccc1  168.475499
2341                                 C=Cc1ccccc1  168.490559
1265                                 C=Cc1ccncc1  174.833420
265                                  C=Cc1ccncc1  174.852873
2400              CC(C)(C)OC(=O)N1CCC(C(=O)O)CC1  208.680001
1621              CC(C)(C)OC(=O)N1CCC(C(=O)O)CC1  207.397372
1184                       CC(C)C[C@@H](N)C(=O)O  224.367726
1759                       CC(C)C[C@@H](N)C(=O)O  224.480050
2324                                      CC(C)I  192.150158
85                                        CC(C)I  192.146393
2885                        CC(C)[C@@H](N)C(=O)O  225.261926
2408                        CC(C)[C@@H](N)C(=O)O  225.268828
21                          CC(C)[C@@H](N)C(=O)O  225.284516
1856                            CC(C)[C@@H](N)CO  233.361812
2813                            CC(C)[C@@H](N)CO  233.363695
1841             CC(C)[C@@H]1CC[C@@H](C)C[C@H]1O  239.017551
1448             CC(C)[C@@H]1CC[C@@H](C)C[C@H]1O  239.014413
1881               CC1(C)[C@H]2CC=C(CO)[C@@H]1C2  204.956990
819                CC1(C)[C@H]2CC=C(CO)[C@@H]1C2  204.956990
1635                  CCCCCCCC/C=C/CCCCCCCC(=O)O  214.106698
2310                  CCCCCCCC/C=C/CCCCCCCC(=O)O  216.249641
262                                           CI  195.299626
853                                           CI  195.293351
2061  CO[C@H]1O[C@H](CO)[C@H](O)[C@H](O)[C@@H]1O  245.235537
1944  CO[C@H]1O[C@H](CO)[C@H](O)[C@H](O)[C@@H]1O  245.222987
1918                         CSCC[C@@H](N)C(=O)O  194.000682
276                          CSCC[C@@H](N)C(=O)O  200.738247
11                        N[C@@H](CC(=O)O)C(=O)O  218.324814
1469                      N[C@@H](CC(=O)O)C(=O)O  218.341129
135                      N[C@@H](CCC(=O)O)C(=O)O  229.915533
475                      N[C@@H](CCC(=O)O)C(=O)O  229.923063
871                            N[C@@H](CO)C(=O)O  229.721005
1730                           N[C@@H](CO)C(=O)O  233.944768
1109                    N[C@@H](Cc1ccccc1)C(=O)O  197.559913
313                     N[C@@H](Cc1ccccc1)C(=O)O  197.526656
2540                         N[C@H]1CCCC[C@@H]1N  218.194919
2194                         N[C@H]1CCCC[C@@H]1N  218.194919
1361                  O=C(/C=C/c1ccccc1)c1ccccc1  146.505154
921                   O=C(/C=C/c1ccccc1)c1ccccc1  146.505781
643                            O=C(O)[C@H]1CCCN1  213.074446
254                            O=C(O)[C@H]1CCCN1  219.567282
1542                           O=C(O)[C@H]1CCCN1  219.566654
914                               O=C(O)c1ccccc1  186.421629
2011                              O=C(O)c1ccccc1  186.426021
2231                                 O=C1C=CCCC1  188.298508
541                                  O=C1C=CCCC1  188.297881
1183                         O=C1OC(=O)c2ncccc21  182.409964
2715                         O=C1OC(=O)c2ncccc21  182.408709
594    OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@@H]1O  231.955564
2381   OC[C@H]1O[C@H](O)[C@H](O)[C@H](O)[C@@H]1O  231.931719
1294                            c1cnc2[nH]ccc2c1  169.528459
1732                            c1cnc2[nH]ccc2c1  169.528459

In [43]:
dataset_new = dataset.drop_duplicates(subset=['SMILES'])
len(dataset_new)

2873

In [44]:
dataset_new

                                            SMILES   Energygap
0                              Cc1ccc(C(F)(F)F)cc1  197.749421
1                                      O=C(O)CCCCl  247.493942
2     CC(C)(Oc1ccc(CCNC(=O)c2ccc(Cl)cc2)cc1)C(=O)O  164.712327
3                                Nc1ccc(Cl)c(Cl)c1  169.027707
4                            CC(C)=CCC[C@@H](C)CCO  209.569808
...                                            ...         ...
2899    c1ccc(P(CCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1  168.649319
2900                               Brc1cccc2sccc12  162.928319
2901               CCOC(=O)N1c2ccccc2C=C[C@@H]1OCC  165.098245
2902                                 c1ccc2sccc2c1  167.958431
2903                                 Cc1cccc(C)c1O  188.369417

[2873 rows x 2 columns]

In [46]:
from rdkit.ML.Descriptors import MoleculeDescriptors

def RDkit_descriptors(smiles):
    
    mols = [Chem.MolFromSmiles(i) for i in smiles] 
    calc = MoleculeDescriptors.MolecularDescriptorCalculator([x[0] for x in Descriptors._descList])
    desc_names = calc.GetDescriptorNames()
    
    Mol_descriptors =[]
    for mol in mols:
       
        mol=Chem.AddHs(mol)
   
        descriptors = calc.CalcDescriptors(mol)
        Mol_descriptors.append(descriptors)
    return Mol_descriptors,desc_names 


Mol_descriptors, desc_names = RDkit_descriptors(dataset_new['SMILES'])

In [47]:
df_with_200_descriptors = pd.DataFrame(Mol_descriptors,columns=desc_names)
df_with_200_descriptors

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,12.550510,12.550510,1.008796,-5.076351,0.546828,160.138,153.082,160.049985,60,0,...,0,0,0,0,0,0,0,0,0,0
1,10.676844,10.676844,1.840718,-3.333333,0.569323,122.551,115.495,122.013457,42,0,...,0,0,0,0,0,0,0,0,0,0
2,13.050084,13.050084,0.722809,-4.111425,0.790287,361.825,341.665,361.108086,132,0,...,0,0,0,0,0,0,0,0,0,0
3,7.402685,7.402685,0.074321,-0.449630,0.582519,162.019,156.979,160.979905,48,0,...,0,0,0,0,0,0,0,0,0,0
4,8.095237,8.095237,1.886963,-4.484184,0.606746,156.269,136.109,156.151415,66,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2868,9.505488,9.505488,0.973292,-3.873136,0.373065,398.426,374.234,398.135324,138,0,...,0,0,0,0,0,0,0,0,0,0
2869,7.651157,7.651157,0.017477,-0.170718,0.625891,213.099,208.059,211.929533,50,0,...,0,0,0,0,0,0,0,1,0,0
2870,13.017078,13.017078,0.325694,-3.813937,0.823664,247.294,230.158,247.120843,96,0,...,0,0,0,0,0,0,0,0,0,0
2871,7.592407,7.592407,0.030556,-0.348333,0.519376,134.203,128.155,134.019021,44,0,...,0,0,0,0,0,0,0,1,0,0
2872,7.522616,7.522616,0.821250,-2.919676,0.557704,122.167,112.087,122.073165,48,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
def morgan_fpts(data):
    Morgan_fpts = []
    for i in data:
        mol = Chem.MolFromSmiles(i) 
        fpts =  AllChem.GetMorganFingerprintAsBitVect(mol,2,2048)
        mfpts = np.array(fpts)
        Morgan_fpts.append(mfpts)  
    return np.array(Morgan_fpts)

In [60]:
Morgan_fpts = morgan_fpts(dataset_new['SMILES'])
Morgan_fpts.shape

(2873, 2048)

In [61]:
Morgan_fingerprints = pd.DataFrame(Morgan_fpts,columns=['Col_{}'.format(i) for i in range(Morgan_fpts.shape[1])])
Morgan_fingerprints

,Col_0,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,...,Col_2038,Col_2039,Col_2040,Col_2041,Col_2042,Col_2043,Col_2044,Col_2045,Col_2046,Col_2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2868,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2869,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2870,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2871,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2872,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
def All_Mordred_descriptors(data):
    calc = Calculator(descriptors, ignore_3D=False)
    mols = [Chem.MolFromSmiles(smi) for smi in data]
    
    df = calc.pandas(mols)
    return df

In [63]:
mordred_descriptors = All_Mordred_descriptors(dataset_new['SMILES'])

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2873/2873 [01:37<00:00, 29.51it/s]

In [64]:
mordred_descriptors.shape

(2873, 1826)